### ISSUE TITLE
input format error

### ISSUE THREAD

**Issue by ymlwww** [Open-Debin/Emotion-FAN#10]
Hi, I changed the input to two classes, angry or not to run your network. However, I encounter:TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not str. 
And the error is here:
File "Demo_AFEW_Attention.py", line 181, in validate
    f, alphas = model(input_var, phrase = 'eval')
File "/Code/Model.py", line 206, in forward
    f = self.conv1(x)
Could you please explain why? Thank you. Besides that, why you partition the input into three parts?

**Comment by ymlwww** [comment]
I have fixed the error by assign the cuda device number. The three parts means K in the paper.

**Comment by jianbaba** [comment]
> I have fixed the error by assign the cuda device number. The three parts means K in the paper.

hi,would you tell me how to fix it, when i use more than 1 gpu,i will meet the problem.thanks

**Comment by Open-Debin** [comment]
@ymlwww @jianbaba 
Merry Christmas, I recently update the Emotion-FAN, new features include data process, environment install, CK+ code, Baseline code, and more detail instructions. Also, you can find the old version directory of Emotion-FAN in the README.md. I hope my new updates can help you greatly. Please see the Emotion-FAN for more details.
