### ISSUE TITLE
Regarding ICIP paper (state-of-the-art)

### ISSUE THREAD

**Issue by vkumar1997** [Open-Debin/Emotion-FAN#14]
The corresponding paper to this repository claims state-of-the-art. However, I have seen other papers who have better accuracy than this paper. 
http://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w10/Acharya_Covariance_Pooling_for_CVPR_2018_paper.pdf

Are you using different metrics because they achieve 59% accuracy?

**Comment by Open-Debin** [comment]
Thanks for your question.

The **59**% accuracy in the paper **CVPR 2018 (your mention)** is cited from another paper, "**Multi-clue fusion for emotion recognition in the wild, ACM ICMI 2016**", but there is no method that achieved 59% in this paper. Could you please find the method which achieves 59% Accuracy. Also, **CVPR 2018 only achieve 46.71**% (**4.47% lower than my method**). Moreover, **ACM ICMI 2016 only achieves 49.22**% (**1.96% lower than my method** with **Single Model**) with **Multiply Model Fusion**.

I want to answer your question, so could you please find the method which achieved 59% accuracy. Also, I would be appreciated if you could read a paper carefully before you ask a question.

**Comment by Open-Debin** [comment]
@vkumar1997 
Merry Christmas, I recently update the Emotion-FAN, new features include data process, environment install, CK+ code, Baseline code, and more detail instructions. Also, you can find the old version directory of Emotion-FAN in the README.md. I hope my new updates can help you greatly. Please see the Emotion-FAN for more details.
