### ISSUE TITLE
Can't extract pre-train model

### ISSUE THREAD

**Issue by Wilfred-Yang** [Open-Debin/Emotion-FAN#19]
Hi, I just follow the instruction to download two pre-train models from Onedrive. However, I can't extract it. And the link from Baidu doesn't exist. Could you reupload the pre-train models again?

**Comment by Open-Debin** [comment]
I just check that the link from Baidu exists. Also, do you mean extract model.pth.tar?

I am sorry that I name it *.tar, which follow the name habit of many torch code. But the model is not tar compressed file. Just use torch.load('model.pth.tar') can load the model.

**Comment by Open-Debin** [comment]
@Wilfred-Yang 
Merry Christmas! I recently update the Emotion-FAN, new features include data process, environment install, CK+ code, and Baseline code. Also, you can find the old version directory of Emotion-FAN in the README.md. I hope my new updates can help you greatly. Please see the Emotion-FAN for more details.

**Comment by Wilfred-Yang** [comment]
Thank you so much to update new details!!
