### ISSUE TITLE
I hope you to provide the final model for AFEW

### ISSUE THREAD

**Issue by chaelin0722** [Open-Debin/Emotion-FAN#33]
Hello , Thanks for sharing updates on Emotion-FAN! I am studying FER and I was impressed by your paper.

I am trying to make demo system using your model, but failed to find the final trained model for AFEW8.0

I just found the weights of Resnet18_FER+_pytorch.pth.tar  and Resnet18_MS1M_pytorch.pth.tar which seems baseline trained model. I want to use your final model to produce a demo for my test. can you provide it? 
Thanks so much!

**Comment by YiiiiZhang** [comment]
hello , i also studying video-based FER and i am try to train this model on AFEW8.0 datasets, but it always overfiting . DId you get the final parameter? or you have any suggestion about that. 
Thanks so much!

**Comment by chaelin0722** [comment]
Unfortunately, I could not find the solution for AFEW. However, I found out other trained weights are working so well in real time condition, I utilized Resnet18_FER+_pytorch.pth.tar and Resnet18_MS1M_pytorch.pth.tar instead.
