### ISSUE TITLE
the consistent of label of the datasets

### ISSUE THREAD

**Issue by jianbaba** [Open-Debin/Emotion-FAN#7]
Hello, if I train on the new dataset with the model you provided on Baidu, do I need to change the label? Because the new dataset is not consistent with the type of expression corresponding to the label of the dataset you trained before.
If I just fine-tune it, is it better to keep the consistency of the label.

**Comment by Open-Debin** [comment]
In general, the classifier must be reset. Hope it helps you.
Thanks for your interested in my project, could you give me a star? thanks.

**Comment by jianbaba** [comment]
of course！

**Comment by Open-Debin** [comment]
@jianbaba 
Merry Christmas, I recently update the Emotion-FAN, new features include data process, environment install, CK+ code, Baseline code, and more detail instructions. Also, you can find the old version directory of Emotion-FAN in the README.md. I hope my new updates can help you greatly. Please see the Emotion-FAN for more details.
